name: SonarCloud analysis & Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  pull-requests: read

jobs:

  deploy:
    runs-on: ubuntu-latest
    if: |
      github.ref == 'refs/heads/master' && (
        github.event_name == 'push' ||
        (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
      )

    steps:
      - name: Trigger Vercel Deploy Hook
        env:
            VERCEL_ENV: production
        run: |
          echo "Deploying to $VERCEL_ENV environment..."
